const Map<String, String> urPK = {
  "Language": "زبان",
  "Tailor Book": "درزی کی کتاب",
  "Home": "گھر",
  "New Record": "نیا ریکارڈ",
  "Name": "نام",
  "Number": "فون نمبر",
  "Length": "لمبائی",
  "Arm": "بازو کی لمبائی",
  "kennel": "موری",
  "Teera": "تیرا",
  "Chest": "چھاتی",
  "boundary": "گھیرا",
  "Chaak": "چاک",
  "ShalwarLength": "شلوار کی لمبائی",
  "Cuff": "کف۔",
  "Aasan": "آسن",
  "Belt": "بیلٹ",
  "Trouser": "پتلون/شلوار",
  "MondaGolai": "مونڈا گولائی",
  "Design": "ڈیزائن",
  "Address": "پتہ",
  "SaveNow": "ابھی محفوظ کریں",
  "ViewDetail": "تفصیل دیکھیں",
  "SearchHere": "یہاں تلاش کریں",
  "Do you really want to delete it?": "کیا آپ واقعی اسے حذف کرنا چاہتے ہیں؟",
  "Call Now": "ابھی کال کریں۔",
  "Yes": "جی ہاں",
  "Cancel": "منسوخ",
  "No Records Found": "ریکارڈ نہیں ملا",
  "Sign Out": "باہر جائیں",
  "paincha": "پائنچہ",
  "Collar tip": "کالر نوک",
  "front pocket": "سامنے کی جیب",
  "side pockets": "طرف کی جیبیں",
  "shalwar pocket": "شلوار کی جیب",
  "BoundaryShape": "گھیراؤ گول/مربع",
};
